name: LiteBansRollback
version: '0.0.1'
main: gg.quartzdev.mc.litebansrollback.LiteBansRollback
api-version: '1.21'
dependencies:
  server:
    CommandAPI:
      load: BEFORE
      required: true
      join-classpath: true
    CoreProtect:
      load: BEFORE
      required: true
      join-classpath: true
    LiteBans:
      load: BEFORE
      required: true
      join-classpath: true